---
title: "STA 475 Project 1"
author: "Lucy Cobble"
date: '2023-03-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(ggplot2)
library(ggmosaic)
library(kableExtra)
library(scales)
library(forcats)
library(nnet)
library(knitr)
```

```{r, message = FALSE}
# read in data and change column names
data <- read_xlsx("eBook_Posttest_Data.xlsx", skip = 1)
colnames(data) <- c("Student_Num","C1_Q1", "C1_Q2", "C1_Q3", "C1_Q4", "C1_Q5A", "C1_Q5B",
                    "C2_Q1", "C2_Q2", "C2_Q3", "C2_Q4", "C2_Q5", "C2_Q6",
                    "C3_Q1", "C3_Q2","C3_Q3","C3_Q4","C3_Q5",
                    "C4_Q1", "C4_Q2", "C4_Q3", "C4_Q4",
                    "C5_Q1", "C5_Q2", "C5_Q3", "C5_Q4", "C5_Q5", "C5_Q6",
                    "C6_Q1", "C6_Q2", "C6_Q3", "C6_Q4", "C6_Q5", "C6_Q6",
                    "C7_Q1", "C7_Q2", "C7_Q3", "C7_Q4", "C7_Q5", "C7_Q6",
                    "C1415_Q1", "C1415_Q2", "C1415_Q3", "C1415_Q4",
                    "C1415_Q5", "C1415_Q6")
# remove NA columns
data <- data[,-c(47:49)]


# rotate the data longer
data_longer <- pivot_longer(data, cols = -c("Student_Num"),
                            names_to = "Chapter_Question",
                            values_to = "Score")

# create variable for health literacy
data_longer <- data_longer %>%
  mutate(Health_Lit = ifelse(Chapter_Question == "C1_Q1" | Chapter_Question =="C1_Q3" |
                               Chapter_Question =="C2_Q1" | Chapter_Question =="C2_Q4" |
                               Chapter_Question =="C2_Q5" | Chapter_Question =="C2_Q6" | 
                               Chapter_Question =="C3_Q1" | Chapter_Question =="C3_Q4" | 
                               Chapter_Question =="C3_Q5" | Chapter_Question =="C4_Q2" |
                               Chapter_Question =="C4_Q3" | Chapter_Question =="C5_Q6" |
                               Chapter_Question =="C6_Q3" | Chapter_Question =="C6_Q6" | 
                               Chapter_Question =="C7_Q6" |  Chapter_Question =="C1415_Q2" |
                               Chapter_Question =="C1415_Q4", "Behavior",
                             ifelse(Chapter_Question == "C1_Q2" | Chapter_Question =="C2_Q3" | 
                                      Chapter_Question =="C3_Q3" | Chapter_Question =="C5_Q3" |
                                      Chapter_Question =="C6_Q1" | Chapter_Question =="C6_Q2" | 
                                      Chapter_Question =="C6_Q4" | Chapter_Question =="C6_Q5", 
                                    "Product",
                                    ifelse(Chapter_Question == "C1_Q5A" | Chapter_Question =="C1_Q5B" | 
                                             Chapter_Question =="C5_Q1" | Chapter_Question =="C5_Q5" | 
                                             Chapter_Question =="C1415_Q1" | Chapter_Question =="C1415_Q6",
                                           "Services",
                                           ifelse(Chapter_Question == "C1_Q4" | Chapter_Question =="C2_Q2" |
                                             Chapter_Question =="C3_Q2" | Chapter_Question =="C4_Q1" |
                                               Chapter_Question =="C4_Q4" | Chapter_Question =="C5_Q2" | 
                                               Chapter_Question =="C5_Q4" | Chapter_Question =="C7_Q1" | 
                                               Chapter_Question =="C7_Q2" | Chapter_Question =="C7_Q3" | 
                                               Chapter_Question =="C7_Q4" | Chapter_Question =="C7_Q5" |
                                               Chapter_Question =="C1415_Q3" | Chapter_Question =="C1415_Q5",
                                             "Information", NA)))))

data_longer2 <- data_longer %>%
  separate(Chapter_Question, c("Chapter","Question"))

lvls <- c('C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C1415')
data_longer2 <- data_longer2 %>%
  mutate(Chapter = factor(Chapter, levels = lvls)) %>%
  arrange(Chapter)

# counts of student scores by chapter
count_scorechap <- table(data_longer2$Chapter, data_longer2$Score)
count_scorechap



#data_longer2$Score <- as.factor(data_longer2$Score)
#data_longer2$Chapter <- as.factor(data_longer2$Chapter)





# count the number of missing scores for each student by chapter
chap_zeros <- data_longer2 %>%
  group_by(Student_Num, Chapter) %>%
  summarize(num_zeros = sum(Score == 0))


# create variable that indicates which students were absent
chap_zeros <- chap_zeros %>%
  group_by(Student_Num, Chapter) %>%
  mutate(Absences = ifelse(Chapter == "C1", ifelse(num_zeros == 6,
                                                   "Absent", "Present"),
                        ifelse(Chapter == "C2", ifelse(num_zeros == 6, 
                                                       "Absent", "Present"),
                            ifelse(Chapter == "C3", ifelse(num_zeros == 5, 
                                                           "Absent", "Present"),
                                ifelse(Chapter == "C4", ifelse(num_zeros == 4, 
                                                               "Absent", "Present"),
                                    ifelse(Chapter == "C5", ifelse(num_zeros == 6, 
                                                                   "Absent", "Present"),
                                        ifelse(Chapter == "C6", ifelse(num_zeros == 6, 
                                                                       "Absent", "Present"),
                                            ifelse(Chapter == "C7", ifelse(num_zeros == 6,
                                                                           "Absent", "Present"),
                                                ifelse(Chapter == "C1415", ifelse(num_zeros == 6,
                                                                                   "Absent", "Present"),
                                                       NA)))))))))


fulldata <- merge(data_longer2, chap_zeros, by = c('Student_Num', 'Chapter'))
lvls <- c('C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C1415')
data_longer2 <- data_longer2 %>%
  mutate(Chapter = factor(Chapter, levels = lvls)) %>%
  arrange(Chapter)

fulldata$Score <- as.factor(fulldata$Score)
fulldata$ScoreAns <- fct_collapse(fulldata$Score, Correct = c('1', '2'), Incorrect = c('0', '3', '4'))

logistic1 <- glm(ScoreAns ~ Absences, data = fulldata, family = 'binomial')
summary(logistic1)
pvals <- summary(logistic1)$coefficients[, c(1,4)]
df1 <- as.data.frame(pvals)
colnames(df1)[2] <- "P Values"
colnames(df1)[1] <- "Coefficients"
kable(df1)


fulldata$ScoreSpell <- fct_collapse(fulldata$Score, Correct = c('1', '3'), Incorrect = c('0', '2', '4'))

logistic2 <- glm(ScoreSpell ~ Absences, data = fulldata, family = 'binomial')
summary(logistic2)
pvals2 <- summary(logistic2)$coefficients[, c(1,4)]
df2 <- as.data.frame(pvals2)
colnames(df2)[2] <- "P Values"
colnames(df2)[1] <- "Coefficients"
kable(df2)


chap_zeros_count <- chap_zeros %>%
  group_by(Chapter, Absences) %>%
  summarize(n = n()) %>%
  pivot_wider(names_from = Absences,
              values_from = n)
kable(chap_zeros_count, col.names = c("Chapter", "Absent", "Present"),
      caption = "Counts of Absences by Chapter") %>%
  kable_styling(full_width = FALSE)


```

```{r}

data_longer2$Score <- as.factor(data_longer2$Score)
ggplot() +
  geom_mosaic(aes(x = product(Chapter), fill = Score), data = data_longer2) + 
  scale_fill_manual(values = c('#E69F00', '#56B4E9', '#009E73', '#F0E442', '#CC79A7'))

ggplot() +
  geom_bar(aes(x = Chapter, fill = Score), position = 'stack', data = data_longer2) + 
  scale_fill_manual(values = c('#E69F00', '#56B4E9', '#009E73', '#F0E442', '#CC79A7'))

ggplot() +
  geom_bar(aes(x = Health_Lit, fill = Score), position = 'stack', data = data_longer2) + 
  scale_fill_manual(values = c('#E69F00', '#56B4E9', '#009E73', '#F0E442', '#CC79A7'))



count_scorechap <- table(data_longer2$Chapter, data_longer2$Score)

```

