---
title: "Oral health"
author: ""
date: "2023-03-01"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(foreign)
library(nnet)
library(ggplot2)
library(reshape2)
library(ggthemes)
library(dplyr)
library(kableExtra)
```


```{r}
# Ziyi: Model fitting (cumulative scores), Descriptive statistics (individual scores)

data <- read_xlsx("eBook Posttest Data.xlsx", skip = 1) #read in data

colnames(data) <- c("Student_Num","C1_Q1", "C1_Q2", "C1_Q3", "C1_Q4", "C1_Q5A", "C1_Q5B",
                    "C2_Q1", "C2_Q2", "C2_Q3", "C2_Q4", "C2_Q5", "C2_Q6",
                    "C3_Q1", "C3_Q2","C3_Q3","C3_Q4","C3_Q5",
                    "C4_Q1", "C4_Q2", "C4_Q3", "C4_Q4",
                    "C5_Q1", "C5_Q2", "C5_Q3", "C5_Q4", "C5_Q5", "C5_Q6",
                    "C6_Q1", "C6_Q2", "C6_Q3", "C6_Q4", "C6_Q5", "C6_Q6",
                    "C7_Q1", "C7_Q2", "C7_Q3", "C7_Q4", "C7_Q5", "C7_Q6",
                    "C1415_Q1", "C1415_Q2", "C1415_Q3", "C1415_Q4",
                    "C1415_Q5", "C1415_Q6") #rename all column 


data <- data[,-c(47:49)] # remove NA columns

data_longer <- pivot_longer(data, cols = -c("Student_Num"),
                            names_to = "Chapter_Question",
                            values_to = "Score") # making data into long form

data_longer <- data_longer %>%
  mutate(Health_Lit = ifelse(Chapter_Question == "C1_Q1" | Chapter_Question =="C1_Q3" |
                               Chapter_Question =="C2_Q1" | Chapter_Question =="C2_Q4" |
                               Chapter_Question =="C2_Q5" | Chapter_Question =="C2_Q6" | 
                               Chapter_Question =="C3_Q1" | Chapter_Question =="C3_Q4" | 
                               Chapter_Question =="C3_Q5" | Chapter_Question =="C4_Q2" |
                               Chapter_Question =="C4_Q3" | Chapter_Question =="C5_Q6" |
                               Chapter_Question =="C6_Q3" | Chapter_Question =="C6_Q6" | 
                               Chapter_Question =="C7_Q6" |  Chapter_Question =="C1415_Q2" |
                               Chapter_Question =="C1415_Q4", "Behavior",
                             ifelse(Chapter_Question == "C1_Q2" | Chapter_Question =="C2_Q3" | 
                                    Chapter_Question =="C3_Q3" | Chapter_Question =="C5_Q3" |
                                    Chapter_Question =="C6_Q1" | Chapter_Question =="C6_Q2" | 
                                    Chapter_Question =="C6_Q4" | Chapter_Question =="C6_Q5", 
                                    "Product",
                             ifelse(Chapter_Question == "C1_Q5A" |Chapter_Question=="C1_Q5B"|
                                    Chapter_Question =="C5_Q1"|Chapter_Question=="C5_Q5"|
                              Chapter_Question=="C1415_Q1"|Chapter_Question=="C1415_Q6","Services",
                             ifelse(Chapter_Question == "C1_Q4"|Chapter_Question =="C2_Q2"|
                                    Chapter_Question =="C3_Q2" | Chapter_Question =="C4_Q1" |
                                    Chapter_Question =="C4_Q4" | Chapter_Question =="C5_Q2"|
                                    Chapter_Question =="C5_Q4" | Chapter_Question =="C7_Q1"|                                            Chapter_Question =="C7_Q2" | Chapter_Question =="C7_Q3" |                                           Chapter_Question =="C7_Q4" | Chapter_Question =="C7_Q5" |
                                    Chapter_Question=="C1415_Q3"|Chapter_Question=="C1415_Q5",
                                          "Information", NA)))))  #create variable for health literacy

data_longer <- data_longer %>%
  separate(Chapter_Question, c("Chapter","Question"))


```


```{r}
#Descriptive statistics 

# function to calculate the mode
get_mode <- function(x) {
  u <- unique(x)
  tab <- tabulate(match(x,u))
  u[tab == max(tab)]
}

data1 <- data_longer %>%
  group_by(Chapter)%>%
  summarize(mean=mean(Score),
            median=median(Score),
            mode=get_mode(Score))

data1 <- data1 %>% 
  pivot_longer(cols=c("mean", "median", "mode"),
                    names_to="summary",
                   values_to="value")

# move rows with Chapter == "C1415" to the end of the dataset
rows_1 <- subset(data1, Chapter == "C1415")
rows_2 <- subset(data1, Chapter != "C1415")
new_data <- rbind(rows_2, rows_1)

#change the x-axis into chapter
new_data %>%
  ggplot(aes(x=Chapter, y=value, group=summary, color=summary)) +
  geom_line(size=1.5)+
  geom_point(size=1)+
  labs(x="Chapter",
       y="Value")+
  ggtitle("Chapter Summary Plot")+
  annotate("text", x=3, y=0.95, label= "bolditalic(overlapping(meidan+mode))",
           col="blue", size=5, parse=TRUE)+
   scale_x_discrete(limits = c("C1", "C2", "C3", "C4", "C5", "C6","C7","C1415"))+
  theme_hc()

```




```{r}
#count of score for students' performance and calculate the mean/median/mode for counts


data_score0 <- data_longer %>%
  filter(Score == 0) %>%
  group_by(Student_Num) %>%
  summarize(Score0 = n()) 

data_score0 <- data_score0 %>%
  summarize(mean=mean(Score0,na.rm = TRUE),
            median=median(Score0,na.rm = TRUE),
            mode=get_mode(Score0))

data_score1 <- data_longer %>%
  filter(Score == 1) %>%
  group_by(Student_Num) %>%
  summarize(Score1 = n())

data_score1 <- data_score1 %>%
  summarize(mean=mean(Score1,na.rm = TRUE),
            median=median(Score1,na.rm = TRUE),
            mode=mean(get_mode(Score1))) # there are two mode, so take the average

data_score2 <- data_longer %>%
  filter(Score == 2) %>%
  group_by(Student_Num) %>%
  summarize(Score2 = n()) 

data_score2 <- data_score2 %>%
  summarize(mean=mean(Score2,na.rm = TRUE),
            median=median(Score2,na.rm = TRUE),
            mode=get_mode(Score2))

data_score3 <- data_longer %>%
  filter(Score == 3) %>%
  group_by(Student_Num) %>%
  summarize(Score3 = n()) 

data_score3 <- data_score3 %>%
  summarize(mean=mean(Score3,na.rm = TRUE),
            median=median(Score3,na.rm = TRUE),
            mode=get_mode(Score3))

data_score4 <- data_longer %>%
  filter(Score == 4) %>%
  group_by(Student_Num) %>%
  summarize(Score4 = n()) 

data_score4 <- data_score4 %>%
  summarize(mean=mean(Score4,na.rm = TRUE),
            median=median(Score4,na.rm = TRUE),
            mode=get_mode(Score4))


data_summary <- rbind(data_score0, data_score1, data_score2,data_score3,data_score4) #combine four table 
data_summary$score_category <- c("0","1","2","3","4")

data_summary1 <- data_summary %>% 
  pivot_longer(cols=c("mean", "median", "mode"),
                    names_to="summary",
                   values_to="value")

data_summary1 %>%
  ggplot(aes(x=score_category, y=value, group=summary, color=summary)) +
  geom_line(size=1.5)+
  geom_point()+
  labs(x="Score",
       y="Count")+
  ggtitle("Summary Plot for Each Score")+
  theme_hc()
```
```{r}
# Model fitting (Chapter)

data_longer$Score <- relevel(factor(data_longer$Score), ref = "4")
Model_chapter <- multinom(Score ~ Chapter, data = data_longer)
summary(Model_chapter)
z <- summary(Model_chapter)$coefficients/summary(Model_chapter)$standard.errors
pval <- (1 - pnorm(abs(z), 0, 1)) * 2
rownames(pval) <- c("0","1","2","3")

kable(round(pval, digits = 4), row.names = TRUE)%>%
  kable_styling()

coef_table <- coef(Model_chapter)
kable(coef_table, format = "markdown", caption = "Coefficients of model")

percent_table <- exp(coef(Model_chapter))
kable(percent_table, format = "markdown")

```


```{r}
#Split data set into correct and incorrect one
data_longer1 <- data_longer

#Split data set into correct and incorrect one
data_longer1$Score <- as.numeric(as.character(data_longer1$Score))  # convert factor to numeric
data_longer1$Score <- ifelse(data_longer1$Score > 1, 0, data_longer1$Score)
data_longer1$Score <- factor(data_longer1$Score)
data_longer1$Chapter <- factor(data_longer1$Chapter)

Model_chapter_logistic <- glm(Score ~ Chapter, data = data_longer1, family = "binomial")
summary(Model_chapter_logistic)

kable(table_pavl, format = "markdown",caption = "P-value of logistic model")

kable(table_logistic, format = "markdown",caption = "Coefficients of logistic model")


```












